project_id = "qlidbycuvuurnalbvfcc"

[auth]
site_url = "https://lco-connect-project.vercel.app"
additional_redirect_urls = [
  "https://lco-connect-project.vercel.app/pages/activate-account.html",
  "https://lco-connect-project.vercel.app/pages/login.html",
  "https://lco-connect-project.vercel.app/*",
  "http://localhost:3000/pages/activate-account.html",
  "http://localhost:3000/*",
  "http://127.0.0.1:3000/*"
]
